### ISSUE TITLE
image not shown on blogroll

### ISSUE THREAD

**Issue by UmbrellaBitcoins** [intelliants/subrion-plugin-personal_blog#6]
Blog image not shown on Blogroll on landing page . Ver 4.1

**Comment by vbezruchkin** [comment]
Hi,

This plugin is obsolete. We don't have it anymore in our new version. See readme note please.
https://github.com/intelliants/subrion-plugin-personal_blog
Instead it transformed into Blog plugin.

What template do you use with it?

Thanks

**Comment by UmbrellaBitcoins** [comment]
Default kickstart! 
I understand, I did not know it was already out.

**Comment by vbezruchkin** [comment]
Yes, we have not announced it officially but we recommend to start using 4.1 version. If you have any issues - please report.

Thanks
